# Generated by Django 5.2 on 2025-04-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imginfo',
            options={'managed': False},
        ),
    ]
